name: Metrics

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/main.yml
  schedule:
    - cron: "0 0 */7 * *"

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
        - name: Generate metrics
          uses: lowlighter/metrics@latest
          with:
            token: ${{ secrets.METRICS_TOKEN }}

            user: UnitLabs
            filename: profile/metrics.svg
            template: classic

            plugin_lines: yes
            plugin_traffic: yes

            plugin_followup: no
            plugin_followup_indepth: yes
            plugin_followup_sections: repositories, user

            plugin_languages: yes
            plugin_languages_details: percentage, lines
            plugin_languages_sections: most-used, recently-used
            plugin_languages_other: true

            plugin_activity: yes
            plugin_activity_limit: 5
            plugin_activity_timestamps: yes